version: '3.8'

services:
  proxy:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - "3050:80"

  backend:
    build:
      dockerfile: Dockerfile
      context: "./api"
    ports:
      - "8080:8080"
    volumes:
      - "./api:/app"
  frontend:
    stdin_open: true
    environment:
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:8080
    build:
      dockerfile: Dockerfile
      context: "./sys-stats"
    ports:
      - "3000:3000"
    volumes:
      - "./sys-stats:/app"
      - "/app/node_modules"
